const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
const source = fs.readFileSync('src/features/chat/chat.slice.ts', 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText;
const context = { exports: {}, require };
vm.runInNewContext(compiled, context);
const { default: reducer, openChat, closeChat, setChatHistory, addChatMessage, addChatReaction, removeChatReaction } = context.exports;
const message = (id, roomId = 'room-a') => ({ id, roomId, userId: 'user', name: 'Listener', text: 'Hello', createdAt: `2026-01-01T00:00:0${id}Z`, requestId: id });
test('chat merges history without duplicates or leaking between rooms', () => {
  let state = reducer(undefined, openChat('room-a'));
  state = reducer(state, addChatMessage(message('2')));
  state = reducer(state, setChatHistory({ roomId: 'room-a', messages: [message('1'), message('2')] }));
  assert.equal(state.messages.length, 2);
  assert.equal(state.messages[0].id, '1');
  assert.equal(state.ready, true);
  state = reducer(state, addChatMessage(message('3', 'room-b')));
  assert.equal(state.messages.length, 2);
  state = reducer(state, addChatReaction({ ...message('3'), emoji: '🔥' }));
  assert.equal(state.reactions.length, 1);
  state = reducer(state, removeChatReaction('3'));
  assert.equal(state.reactions.length, 0);
  state = reducer(state, openChat('room-b'));
  assert.equal(state.messages.length, 0);
  assert.equal(state.ready, false);
  state = reducer(state, setChatHistory({ roomId: 'room-a', messages: [message('1')] }));
  assert.equal(state.messages.length, 0);
  assert.equal(reducer(state, closeChat()).roomId, null);
});
